//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package ru.poloniumarts.netutils;

import android.app.Activity;
import android.content.Context;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.widget.ListAdapter;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class CursorScrollListener_
    extends CursorScrollListener
{

    private Context context_;
    private Handler handler_ = new Handler();

    private CursorScrollListener_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        ((ViewMapperAdapter_) adapter).afterSetContentView_();
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        adapter = ViewMapperAdapter_.getInstance_(context_);
    }

    public static CursorScrollListener_ getInstance_(Context context) {
        return new CursorScrollListener_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void notifyDataSetChanged(final ListAdapter adapter, final String direction, final int numOfNewElements) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    CursorScrollListener_.super.notifyDataSetChanged(adapter, direction, numOfNewElements);
                } catch (RuntimeException e) {
                    Log.e("CursorScrollListener_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void getNextDataPortion(final int startId, final String direction, final ListAdapter listAdapter) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    CursorScrollListener_.super.getNextDataPortion(startId, direction, listAdapter);
                } catch (RuntimeException e) {
                    Log.e("CursorScrollListener_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
