//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package ru.poloniumarts.netutils;

import android.app.Activity;
import android.content.Context;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import org.json.JSONObject;

public final class ErrorMapper_
    extends ErrorMapper
{

    private Context context_;
    private Handler handler_ = new Handler();

    private ErrorMapper_(Context context) {
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        root = ((View) findViewById(ru.poloniumarts.netutlis.R.id.root));
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        if (context_ instanceof Activity) {
            activity = ((Activity) context_);
        }
        context = context_;
    }

    public static ErrorMapper_ getInstance_(Context context) {
        return new ErrorMapper_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void map(final JSONObject json) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ErrorMapper_.super.map(json);
                } catch (RuntimeException e) {
                    Log.e("ErrorMapper_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
