//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package ru.poloniumarts.netutils;

import android.app.Activity;
import android.content.Context;
import android.util.AttributeSet;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class MapperItemView_
    extends MapperItemView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public MapperItemView_(Context context) {
        super(context);
        init_();
    }

    public MapperItemView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public MapperItemView_(Context context, AttributeSet attrs, int defStyle) {
        super(context, attrs, defStyle);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        mapper = ViewMapper_.getInstance_(context_);
    }

    private void afterSetContentView_() {
        ((ViewMapper_) mapper).afterSetContentView_();
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static MapperItemView build(Context context) {
        MapperItemView_ instance = new MapperItemView_(context);
        instance.onFinishInflate();
        return instance;
    }

    public static MapperItemView build(Context context, AttributeSet attrs) {
        MapperItemView_ instance = new MapperItemView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static MapperItemView build(Context context, AttributeSet attrs, int defStyle) {
        MapperItemView_ instance = new MapperItemView_(context, attrs, defStyle);
        instance.onFinishInflate();
        return instance;
    }

}
